import Head from 'next/head'
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { SettingsContent, AboutPageContent } from '@/helpers/data_utils';
import { useState, useEffect } from 'react';

import './About.scss';
import './About.responsive.scss';

import AboutBanner from '@/components/AboutBanner/AboutBanner';
import AboutStory from '@/components/AboutStory/AboutStory';
import HomePartner from '@/components/HomePartner/HomePartner';
import AboutOurValue from '@/components/AboutOurValue/AboutOurValue';

export default function AboutUsPage(props) {
  const {aboutData} = props.aboutContent.data;
  const settingsContent = props.settingsContent;
  const [initialRenderComplete, setInitialRenderComplete] = useState(false);
  useEffect(() => {
    setInitialRenderComplete(true);
  }, []);
if (!initialRenderComplete) {
      return null;
} else {   
  
  return (
        <>
          <Head>
            <title>About us page</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Header settings={settingsContent}></Header>
          <AboutBanner aboutData={aboutData} />
          <AboutStory aboutData={aboutData} />
          <HomePartner />
          <AboutOurValue  aboutData={aboutData} />
          <Footer></Footer>
        </>
      );

  }
}
export async function getServerSideProps({ req, res }){
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  return {
      props:{
        aboutContent: await AboutPageContent(),
        settingsContent : await SettingsContent(),
      }
  };
}

