
export const dynamic = "force-dynamic"; // this is the fix
import Head from 'next/head';

import HomeAppSection from '@/components/HomeAppSection/HomeAppSection';
import HomeBanner from '@/components/HomeBanner/HomeBanner';
import HomeVideoSection from '@/components/HomeVideoSection/HomeVideoSection';
import HomeCaseStudy from '@/components/HomeCaseStudy/HomeCaseStudy';

import HomeTestimonials from '@/components/HomeTestimonials/HomeTestimonials';
import HomeSuccessProduct from '@/components/HomeSuccessProduct/HomeSuccessProduct';
import HomePartner from '@/components/HomePartner/HomePartner';
import { HomePageContent, SettingsContent } from '@/helpers/data_utils';
import Container from '@/containers/Container';
import config from '@/helpers/config';



const HomePage = (props) => {
        const {  homeData, portfolioData, testimonialData  } = props.dataHomePage.data;
        return (
          <>
            <Head>
              <title>home page</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            
             
                <HomeBanner homeContent={homeData.content} />
                <HomeVideoSection homeContent={homeData.content} />
                <HomeCaseStudy portfolioData={portfolioData} />
                <HomeAppSection homeContent={homeData.content} />
                {/* <HomeTechnology /> */}
                <HomeTestimonials testimonialData={testimonialData} />
                <HomeSuccessProduct />
                <HomePartner /> 
                 
            
          </>
        )
}
export default Container(HomePage);

export async function getStaticProps({ req, res }){
  
  
   
  return {
      props:{
        settingsContent : await SettingsContent(),
        dataHomePage: await HomePageContent(),
      },
      revalidate:config().revalidate
  };
}
