
export const dynamic = "force-dynamic"; // this is the fix
import Head from 'next/head';

import HomeAppSection from '@/components/HomeAppSection/HomeAppSection';
import HomeBanner from '@/components/HomeBanner/HomeBanner';
import HomeVideoSection from '@/components/HomeVideoSection/HomeVideoSection';
import HomeCaseStudy from '@/components/HomeCaseStudy/HomeCaseStudy';

import HomeTestimonials from '@/components/HomeTestimonials/HomeTestimonials';
import HomeSuccessProduct from '@/components/HomeSuccessProduct/HomeSuccessProduct';
import HomePartner from '@/components/HomePartner/HomePartner';
import { useState, useEffect } from 'react';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

import { HomePageContent, SettingsContent } from '@/helpers/data_utils';


 export default function Home(props) {
  const {  homeData, portfolioData, testimonialData  } = props.dataHomePage.data;
  const settingsContent = props.settingsContent;
  

  // console.log("==========================");
  // console.log(settingsContent);


  const [initialRenderComplete, setInitialRenderComplete] = useState(false);
  useEffect(() => {
    setInitialRenderComplete(true);
  }, []);
if (!initialRenderComplete) {
      return null;
} else {
  return (
    <>
      <Head>
        <title>home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header settings={settingsContent}></Header>
          <HomeBanner homeContent={homeData.content} />
          <HomeVideoSection homeContent={homeData.content} />
          <HomeCaseStudy portfolioData={portfolioData} />
          <HomeAppSection homeContent={homeData.content} />
          {/* <HomeTechnology /> */}
          <HomeTestimonials testimonialData={testimonialData} />
          <HomeSuccessProduct />
          <HomePartner /> 
          <Footer></Footer>
      
    </>
  )
}
  
}
export async function getServerSideProps({ req, res }){
  res.setHeader(
    'Cache-Control',
    'public, s-maxage=10, stale-while-revalidate=59'
  )
  return {
      props:{
        settingsContent : await SettingsContent(),
         dataHomePage: await HomePageContent(),
      }
  };
}
